---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: true
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: This an implementation of Jsonnet in pure Go.
app_name: jsonnet
app_repo: https://github.com/google/go-jsonnet
app_type: standalone
app_website: https://github.com/google/go-jsonnet
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\\.tar\\.gz|\\.tgz|\\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/google/go-jsonnet/releases/download/v{version}/checksums.txt
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/google/go-jsonnet/releases/download/v{version}/go-jsonnet_{version}_{os}_{arch}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    jsonnet: bin/jsonnet
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-go-jsonnet
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-go-jsonnet.git
source_enabled: true
source_type: git
source_url: https://github.com/google/go-jsonnet.git
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    arm64: x86_64
    armv5*: armv6
    armv6*: armv6
    armv7*: armv6
    i386: i386
    i686: i386
    powerpc64le: x86_64
    ppc64le: x86_64
    x86: '386'
sys_ext_enabled: false
sys_os_enabled: true
sys_os_yaml:
    darwin: Darwin
    linux: Linux
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
